# This is the location of the bot's token. The token must be placed on
# the first line of the file
token_file: config/token.txt

# It's the prefix.. What more do I need to say?
command_prefix: "'"

# bot devs, gives special perms in some instances
developers:
  - 137001076284063744

# Whether all cogs should be loaded by default
load_by_default: true

# The cogs to not follow the default
# If load_by_default is true, these are the cogs which are not loaded
# If load_by_default is false, these cogs are loaded
# Useful for development
# This should contain just the cog name, and not be prefixed with cogs.
cogs: 
  - 
